"""add_telegram_link_fields

Revision ID: bd36e690e3eb
Revises: d9669086ad0f
Create Date: 2026-05-02 12:15:31.200224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd36e690e3eb'
down_revision: Union[str, Sequence[str], None] = 'd9669086ad0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_link_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('telegram_link_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_telegram_link_code'), 'users', ['telegram_link_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_link_code'), table_name='users')
    op.drop_column('users', 'telegram_link_expires_at')
    op.drop_column('users', 'telegram_link_code')
    # ### end Alembic commands ###
